services:
  productoDB:
    image: mysql:5.7
    container_name: productoDB
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=productoDB
    volumes:
      - ./db/productodb/:/docker-entrypoint-initdb.d

  usuarioDB:
    image: mysql:5.7
    container_name: usuarioDB
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=usuarioDB
    volumes:
      - ./db/usuariodb/:/docker-entrypoint-initdb.d

  ordenDB:
    image: mysql:5.7
    container_name: ordenDB
    ports:
      - "32002:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=ordenDB
    volumes:
      - ./db/ordendb/:/docker-entrypoint-initdb.d

  usuarios:
    build: ./microservicios/usuarios
    container_name: usuarios
    ports:
      - "3001:3001"
    links:
      - usuarioDB

  productos:
    build: ./microservicios/productos
    container_name: productos
    ports:
      - "3002:3002"
    links:
      - productoDB

  ordenes:
    build: ./microservicios/ordenes
    container_name: ordenes
    ports:
      - "3003:3003"
    links:
      - productoDB
      - usuarioDB
      - usuarios
      - productos

  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"
    links:
      - usuarios
      - productos
      - ordenes

